export enum EstadoProcesoEnums {
    PROCESO_POR_AUTORIZAR="PROCESO_POR_AUTORIZAR",
    PROCESO_PENDIENTE='PROCESO_PENDIENTE',
    PROCESO_CON_ERROR='PROCESO_CON_ERROR',
    PROCESO_EN_PROCESO='PROCESO_EN_PROCESO',
    PROCESO_FINALIZADO='PROCESO_FINALIZADO'
}